# This is a basic workflow to help you get started with Actions

name: Build site and deploy to S3 bucket

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ] # <-- Change to another branch, it you don't want to work on another branch

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-18.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    # Intall Hugo
    - name: Setup Hugo # <-- installing Hugo on virtual machine
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.88.1'
        extended: true

    # Builds jiangzhenling.com repo
    - name: Build Hugo # <-- Biulding website and adding files to ./public
      run: hugo

    # Deploys built website to S3
    - name: Deploy to S3 # <-- use build-in deploy function to add files to S3 and create invalidations
      run: hugo deploy --force --maxDeletes -1 --invalidateCDN
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.WOWCHEMY_USERNAME }} # <-- Change to the name you gave the AWS key secret
        AWS_SECRET_ACCESS_KEY: ${{ secrets.WOWCHEMY_PASSWORD }} # <-- Change to the name you gave the AWS passwd secret
